language: "node_js"
node_js:
- 9
sudo: required
script:
- npm install
- npm run build
deploy:
  on:
    branch: master
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: survey.vatusa.net
  region: us-west-2
  skip_cleanup: true
  local_dir: dist
  acl: public_read
